sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '10'
  - '11'
  - '8'
   
after_success:
  - yarn semantic-release
  
branches:
  except:
    - /^v\d+\.\d+\.\d+$/


script:
  - yarn test
  - yarn coveralls

